site_name: Energenie
theme: united
site_url: https://pythonhosted.org/energenie/
repo_url: https://github.com/bennuttall/energenie/
site_description: Remotely control power sockets from the Raspberry Pi
site_author: Ben Nuttall
site_favicon: img/favicon.ico
site_dir: pythonhosted
pages:
- [index.md, Home]
- [about.md, About]
- [installing.md, Installing]
- [examples/index.md, Examples, Examples]
- [examples/web.md, Examples, Web Application]
- [reference.md, Reference]
